---
title: "pr6"
---

# Цель работы

1.  Освоить базовые подходы процессов OSINT
2.  Освоить современные интрументы поиска и сбора информации
3.  Освоить инструменты совместной работы в ходе аналитической деятельности

# Исходные данные

1.  Windows 10
2.  Сеть интернет (открытые источники информации)

# План работы

1.  Собрать информацию о Инфосистемы Джет и их продуктах
2.  Собрать информацию о технологиях, применяемых для защиты информации
3.  Собрать информацию о сотрудниках
4.  Сформировать представление о рынке отечественных решений ИБ

# Ход работы:

## 1. Полное название компании

АО "Инфосистемы Джет"

> [https://www.audit-it.ru/contragent/1027700121195_ao-infosistemy-dzhet](https://www.list-org.com/company/59623)

## 2. Основные направления деятельности компании

**Направления и услуги:**\
Информационная безопасность\
Производственная безопасность\
ИТ-инфраструктура\
Разработка ПО и бизнес приложений\
Сети и инженерная инфраструктура\
Сервис и аутсорсинг\
Машинное обучение и ИИ\
Биометрия

**Отрасли**

Гос. структуры\
Финансы и страхование\
Энергетика\
Телекоммуникации\
Промышленность\
Ритейл\
Нефтегазовая индустрия\
Строительство и транспорт

**Используемые технологии и языки программирования**

Apache\
Astra linux\
C/C++\
Go\
PostgreSQL\
Python\
Java\
Javascript\
Swift\


**Продукты:**

JET GALATEA- Работа
с потоками данных, управления
ML-моделями и их интеграции
в другие бизнес-системы\
JET DETECTIVE-AI-based универсальное
решение по противодействию
мошенничеству\
JET SIGNAL-Система управления инцидентами ИБ\
JET PLUTON-AI-based решение для контроля
сетевого траффика, обнаружения
атак и выявления угроз\
JET BI-Доступное и быстро
инсталлируемое решение
для импортозамещения систем
бизнес-аналитики с интуитивно
понятной визуализацией данных\
JET CRM-Доступное и быстро
инсталлируемое решение
для импортозамещения систем
работы с клиентами.\
JET CAPACITY-Прогнозирование требований к ИТ-мощностям в зависимости от бизнес-показателей\
JET CENTURION-Решение для ситуационных центров
и мультифункциональная платформа
для цифровизации образовательного
процесса в ВУЗах

## 3. Основные клиенты

> (https://jet.su/projects/)

ancor\
Beeline\
ВТБ\
Ликард\
Министерство обороны РФ\
НЛМК\
Норникель\
Почта банк и почта россии\
РСА\
Росбанк\
Роскомнадзор\
РУСАГРО\
РИВ ГОШ\
СБЕР Банк

## 4. Основные веб-сайты компании и её продуктов

**Сайты**

> https://jet.su/

> https://jet.su/projects/

> https://new-retail.ru/upload/iblock/515/515ff11b8b7de1b9e4337f17c4f97e56.pdf

## 5. Публичные сотрудники компании и соц-медиа

**Список предстоящих мероприятий**

> https://www.jetinfo.ru/events/

**Сотрудники:**

Генеральный директор - *Владимир Елисеев*

Заместитель генерального директора, коммерческий директор - *Андрей Самойлов*

Директор технического центра - *Юлия Кошкина*

Директор по работе с персоналом - *Ольга Ковардакова*

Директор по цифровизации - *Иванов Алексей*

Руководитель дирекции вычислительных комплексов, сервиса и аутсорсинга - *Павленко Антон*

Руководителя департамента мониторинга и реагирования центра - *Рината Сагирова*

Эксперт центра мониторинга и реагирования на инциденты ИБ - *Валерия Суворова*

Руководитель группы консалтинга центра ИБ - *Кирилл Стадухин*

Начальник отдела по работе с заказчиками - *Андрей Конин*

Директор центра управления данными ИТ - *Дмитрий Кулагин*

Начальник отдела по противодействию мошенничеству - *Алексей Сизов*

Технический директор центра инновационных технологий и решений - *Павел Романченко*

Dедущий специалист Центра машинного обучения ИТ - *Александра Царева*

**Социальные сети и блоги**

> VK-https://vk.com/jetinfosystems

> Telegram-https://t.me/jetinfosystems

> Habr-https://habr.com/ru/companies/jetinfosystems/profile/

> Securitylab - https://www.securitylab.ru/blog/company/jetinfosystems/

> vs.ru - https://vc.ru/u/536956-infosistemy-dzhet

**Почты:**

> pr\@jet.su

> info\@jet.su

## 6. Уникальные достижения

1)№1 на рынке ИТ-аутсорсинга в России (TAdviser, 2022 г.)\
2)№1 в ретинге крупнейших поставщиков инфраструктуры дата-центров(CNews Analytics,2022 г.)\
3)Топ-3 в рейтинге крупнейших интеграторов в области защиты информации (CNews Analytics, 2021 г.)\
4)№2 среди крупнейших поставщиков для российских банков (Tadviser 2022г.)\
5)№2 среди крупнейших поставщиков для промышленности (Tadviser 2022г.)


# Вывод

В данной работе я ознакомилася с базовыми подходами OSINT через поиск и изучение информации о деятельность компании Инфосистемы Джет и компании в целом. Информацию удалось собрать в достаточном объёме, используя современные интрументы поиска и открытые источники информации.
